### ISSUE TITLE
Release 0.6.1

### ISSUE THREAD

**Issue by oleksSol** [psibi/rucredstash#12]
Hey @psibi please release that version, because compatibility is crucial for my use case.

Thanks!

**Comment by psibi** [comment]
@oleksSol Sorry, for the deplay. Published it now:

* crate: https://crates.io/crates/credstash/0.6.1
* tag: https://github.com/psibi/rucredstash/releases/tag/v0.6.1

**Comment by psibi** [comment]
Closing the issue now as a release has been made.
