### ISSUE TITLE
rucredstash in nixpkgs?

### ISSUE THREAD

**Issue by ketzacoatl** [psibi/rucredstash#17]
Hi @psibi,

Would you like to see `rucredstash` in `nixpkgs`?

**Comment by psibi** [comment]
Sure, that would be nice!

**Comment by ketzacoatl** [comment]
@psibi ok, what would you like to see for that? There are a couple questions: is there a nix derivation in this repo that is used to build the package, or do we rely only on what is in the `default.nix` in `nixpkgs`? would you like to maintain the entry in `nixpkgs`? I can get a `default.nix` going in `nixpkgs` if you like, or I can leave it to you. LMK what you would like to see.

**Comment by psibi** [comment]
@ketzacoatl 

>  is there a nix derivation in this repo that is used to build the package, or do we rely only on what is in the default.nix in nixpkgs?

No, I haven't use nix infrastructure to build this. So I have no idea. With haskell, there is `cabal2nix` which automates most of the stuff, I'm assuming something like that will exist for Rust too. But I haven't really looked into it.

> would you like to maintain the entry in nixpkgs?  I can get a default.nix going in nixpkgs if you like, or I can leave it to you.

I think you can go ahead by adding it in nixpkgs. If you rather want me to do, I can try to do it too. :-)

**Comment by ketzacoatl** [comment]
OK, I have a WIP `default.nix` in a `nixpkgs` fork. It's based on what I see for other rust packages in `nixpkgs`.

When building, nix barks at me about `Cargo.lock`:
```
building '/nix/store/ij0mrf9dclas98bfzdncx0cynnvgp47f-rucredstash-v0.8.0-vendor.tar.gz.drv'...
unpacking sources                                                                                    
unpacking source archive /nix/store/k0fikyycbypg278c6j2r5fcij3bsjsfj-source      
source root is source                                                                                
patching sources                                                                                     
building                                                                                             
                                                                                                     
ERROR: The Cargo.lock file doesn't exist                                                             
                                                                                                     
Cargo.lock is needed to make sure that cargoSha256 doesn't change                                                                                                                                          
when the registry is updated.                                                                        
                                                                                                     
builder for '/nix/store/ij0mrf9dclas98bfzdncx0cynnvgp47f-rucredstash-v0.8.0-vendor.tar.gz.drv' failed with exit code 1
cannot build derivation '/nix/store/ka5s0k5688nkkxmx6g022i4qzb9q9ycz-rucredstash-v0.8.0.drv': 1 dependencies couldn't be built
```
But I see that is in your `.gitignore`, so would it be ok to add the current `Cargo.lock` to the repo for nix, or would that cause problems with other things?

**Comment by psibi** [comment]
> But I see that is in your .gitignore, so would it be ok to add the current Cargo.lock to the repo for nix, or would that cause problems with other things?

I think that's okay to put in the git repository since we are building a binary: https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html

I'm willing to accept a PR fixing `.gitignore` and adding the lock file to the repository ? Thank you!

**Comment by psibi** [comment]
Fixed via https://github.com/psibi/rucredstash/pull/18

**Comment by psibi** [comment]
I have added rucredstash to nixpkgs: https://github.com/NixOS/nixpkgs/pull/155135
