### ISSUE TITLE
 "digest column is missing" error

### ISSUE THREAD

**Issue by knnmran** [psibi/rucredstash#22]
getting  "digest column is missing" error when trying to use "get_secret" function.

attribute names in dynamo table: 
- name
- version
- contents
- hmac
- key

notes:
- able to see secrets using "list_secrets" function
- using this lib in nodejs code https://www.npmjs.com/package/nodecredstash
- digest should be SHA256

**Comment by lvn-hasky-dragon** [comment]
I want to bring this change along in the newer version: https://github.com/psibi/rucredstash/pull/24

So probably once the CI passes, I will merge it and do a release.

**Comment by psibi** [comment]
I want to bring this change as part of next version: https://github.com/psibi/rucredstash/pull/24

Once the CI passes, I will merge it and make a new release.

**Comment by psibi** [comment]
The changes has been release to crates.io.
